// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nicolas Wehmeyer
'use strict';
const specs=[[-24,24,0,.01,'st'],[.5,2,1,.001,'×'],[-12,12,0,.01,'st'],[0,100,100,.1,'%'],[-60,6,0,.1,'dB'],[0,2,0,1,''],[0,2,2,1,''],[0,1,0,1,'']];
const values=specs.map(x=>x[2]),$=id=>document.getElementById(id);
const {norm,actual,arc,bindKnobs,drawWaveform}=createChronoBentControls({specs,values,send,gesture,format});
let currentMode=0,captured=0,activity=Array(256).fill(0);
function bridge(message){if(typeof IPlugSendMsg==='function')IPlugSendMsg(message);}
function gesture(i,begin){bridge({msg:begin?'BPCFUI':'EPCFUI',paramIdx:i});}
function send(i,value){if(i===1&&currentMode!==2)return;if(i===2&&values[7]===0)send(7,1);const s=specs[i];values[i]=Math.max(s[0],Math.min(s[1],Math.round(value/s[3])*s[3]));bridge({msg:'SPVFUI',paramIdx:i,value:norm(i,values[i])});paint(i);}
function format(i,value){if(i===0||i===2)return`${value>0?'+':value<0?'−':''}${Math.abs(value).toFixed(2)} st`;if(i===1)return`${value.toFixed(3)} ×`;if(i===3)return`${value.toFixed(1)} %`;return`${value.toFixed(1)} dB`;}
function paint(i){const el=document.querySelector(`.knob-unit[data-param="${i}"]`);if(el){const n=norm(i,values[i]);el.style.setProperty('--rotation',`${-135+270*n}deg`);el.querySelector('.fill').setAttribute('d',arc(n));el.querySelector('.knob').setAttribute('aria-valuenow',values[i]);el.querySelector('.knob').setAttribute('aria-valuetext',format(i,values[i]));if(document.activeElement!==el.querySelector('.value'))el.querySelector('.value').value=format(i,values[i]);}if(i===6)$('transients').selectedIndex=values[i];if(i===7)$('formants').setAttribute('aria-pressed',String(!!values[i]));}
bindKnobs();
function mode(value){gesture(5,true);send(5,value);gesture(5,false);}
$('tune').addEventListener('click',()=>bridge({msg:'SAMFUI',msgTag:20,ctrlTag:-1,data:''}));
$('capture').addEventListener('click',()=>mode(values[5]===1?2:1));
$('loop').addEventListener('click',()=>mode(currentMode===2?0:2));
$('live').addEventListener('click',()=>mode(0));
$('formants').addEventListener('click',()=>{gesture(7,true);send(7,values[7]?0:1);gesture(7,false);});
$('transients').addEventListener('change',()=>{gesture(6,true);send(6,$('transients').selectedIndex);gesture(6,false);});
window.SPVFD=(i,value)=>{if(!specs[i]||!Number.isFinite(value))return;const s=specs[i];values[i]=Math.max(s[0],Math.min(s[1],Math.round(actual(i,value)/s[3])*s[3]));paint(i);};
window.SAMFD=(tag,size,data)=>{if(tag!==100)return;try{const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));update(JSON.parse(new TextDecoder().decode(bytes)));}catch(error){$('notice').textContent='Display update unavailable';}};
window.SCMFD=()=>{};window.SMMFD=()=>{};window.SSMFD=()=>{};
function update(s){currentMode=s.mode;captured=s.captured;const recording=s.mode===1,looping=s.mode===2;$('tune').disabled=!s.captured||recording;$('tune').textContent=s.tuned?'NOTE STUDIO · ON ↗':'NOTE STUDIO ↗';document.body.classList.toggle('recording',recording);$('source-name').textContent=recording?'Capturing your track…':looping?'Captured passage':'Live input';$('source-meta').textContent=looping?`${s.captured.toFixed(2)} SEC / INDEPENDENT PITCH & TIME`:recording?`${(s.progress*30).toFixed(1)} / 30 SEC`:'PITCH & TIMBRE · IN THE FLOW';$('source-badge').textContent=recording?'REC':looping?'LOOP':'LIVE';$('status').textContent=s.error?s.error.toUpperCase():recording?'LISTENING · PRESS STOP & LOOP WHEN YOU HAVE IT':looping?'YOUR MOMENT, REIMAGINED':s.ready?'READY FOR YOUR TRACK':'STARTING EFFECT…';$('latency').textContent=`${s.latency.toFixed(1)} ms · LATENCY`;$('progress').style.width=recording?`${100*s.progress}%`:'0';$('capture-label').textContent=recording?'STOP & LOOP':captured?'CAPTURE AGAIN':'CAPTURE INPUT';$('loop').disabled=!captured;$('loop').setAttribute('aria-pressed',String(looping));$('loop').querySelector('span').textContent=looping?'LOOPING':'PLAY CAPTURE';$('live').setAttribute('aria-pressed',String(!looping&&!recording));$('capture-title').textContent=recording?'Keep the part that moves you.':looping?'A moment worth staying in.':'Catch it. Bend it. Stay a while.';$('capture-description').textContent=recording?'The live effect stays audible while your passage records.':looping?'Time changes this captured loop. Live input remains available.':'Capture up to 30 seconds, then explore pitch, time and timbre.';$('time-control').classList.toggle('inactive',!looping);$('time-control').querySelector('.knob').tabIndex=looping?0:-1;$('time-control').querySelector('.knob').setAttribute('aria-disabled',String(!looping));$('time-control').querySelector('.value').disabled=!looping;$('time-hint').textContent=looping?'Captured playback speed':'Capture to change time';$('input-meter').style.width=`${Math.min(100,s.input*100)}%`;$('output-meter').style.width=`${Math.min(100,s.output*100)}%`;$('in-value').textContent=s.input>1e-6?(20*Math.log10(s.input)).toFixed(0):'−∞';$('out-value').textContent=s.output>1e-6?(20*Math.log10(s.output)).toFixed(0):'−∞';activity.push(s.input||0);activity.shift();drawWaveform($('waveform'),looping?s.waveform:activity);$('playhead').hidden=!looping;$('playhead').style.left=`${Math.max(0,Math.min(1,s.position))*100}%`;const warning=s.error||(s.underruns||s.dropped?'STREAM UNDERRUN · ALIGNED DRY FALLBACK':s.invalid?'INVALID INPUT SAMPLES REMOVED':'');$('notice').textContent=warning||'LIVE PITCH & TIMBRE · CAPTURED TIME';$('notice').classList.toggle('error',!!warning);}
values.forEach((_,i)=>paint(i));
update({mode:0,ready:false,captured:0,progress:0,position:0,input:0,output:0,waveform:activity,latency:216,error:'',underruns:0,dropped:0,invalid:0});
if(new URLSearchParams(location.search).has('preview')){const waveform=Array.from({length:256},(_,i)=>(.15+.4*Math.abs(Math.sin(i*.43))+.2*Math.abs(Math.sin(i*.037)))*Math.sin(Math.PI*(i+1)/258));update({mode:2,ready:true,captured:4.25,progress:0,position:.36,input:.2,output:.35,waveform,latency:216,error:'',underruns:0,dropped:0,invalid:0});}
