// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nicolas Wehmeyer
'use strict';
window.createChronoBentControls=({specs,values,send,gesture,format})=>{
function norm(i,value){const s=specs[i];return Math.pow(Math.max(0,Math.min(1,(value-s[0])/(s[1]-s[0]))),1/(s[5]||1));}
function actual(i,value){const s=specs[i];return s[0]+Math.pow(Math.max(0,Math.min(1,value)),s[5]||1)*(s[1]-s[0]);}
function arc(f){const a=-135*Math.PI/180,b=(-135+270*Math.max(.00001,f))*Math.PI/180;const point=t=>[60+51*Math.sin(t),60-51*Math.cos(t)];const p=point(a),q=point(b);return `M${p} A51,51 0 ${f>2/3?1:0},1 ${q}`;}
function bindKnobs(){
for(const el of document.querySelectorAll('.knob-unit')){const i=Number(el.dataset.param),knob=el.querySelector('.knob'),input=el.querySelector('.value');el.querySelector('.track').setAttribute('d',arc(1));knob.setAttribute('aria-valuemin',specs[i][0]);knob.setAttribute('aria-valuemax',specs[i][1]);let drag=null;knob.addEventListener('pointerdown',e=>{drag={y:e.clientY,value:norm(i,values[i]),id:e.pointerId};knob.setPointerCapture(e.pointerId);gesture(i,true);});knob.addEventListener('pointermove',e=>{if(!drag)return;const diff=(drag.y-e.clientY)/(e.shiftKey?1800:220);send(i,actual(i,drag.value+diff));});const end=()=>{if(drag){gesture(i,false);drag=null;}};knob.addEventListener('pointerup',end);knob.addEventListener('pointercancel',end);knob.addEventListener('lostpointercapture',end);knob.addEventListener('dblclick',()=>{gesture(i,true);send(i,specs[i][2]);gesture(i,false);});knob.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();gesture(i,true);send(i,e.key==='Home'?specs[i][0]:e.key==='End'?specs[i][1]:actual(i,norm(i,values[i])+(['ArrowUp','ArrowRight'].includes(e.key)?1:-1)*(e.shiftKey?.001:.01)));gesture(i,false);});let selectAll=false;input.addEventListener('focus',()=>{input.value=values[i].toFixed(i===1?3:i<3?2:1);input.select();selectAll=true;});input.addEventListener('mouseup',e=>{if(selectAll){selectAll=false;e.preventDefault();}});input.addEventListener('change',()=>{let value=Number.parseFloat(input.value.replace('−','-'));if(specs[i][4]==='ms'&&/\bs\b/.test(input.value))value*=1000;if(Number.isFinite(value)){gesture(i,true);send(i,value);gesture(i,false);}input.blur();});input.addEventListener('blur',()=>{input.value=format(i,values[i]);});input.addEventListener('keydown',e=>{selectAll=false;if(e.key==='Enter'||e.key==='Escape')input.blur();});}
}
function drawWaveform(canvas,wave){const ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#496a612b';ctx.lineWidth=1;for(let i=0;i<=16;++i){ctx.beginPath();ctx.moveTo(i*w/16,18);ctx.lineTo(i*w/16,h-18);ctx.stroke();}ctx.beginPath();ctx.moveTo(0,h/2);ctx.lineTo(w,h/2);ctx.stroke();const g=ctx.createLinearGradient(0,0,w,0);g.addColorStop(0,'#6dd4c4');g.addColorStop(.6,'#91cdb5');g.addColorStop(1,'#cbb591');ctx.fillStyle=g;const max=Math.max(.001,...wave);for(let i=0;i<wave.length;++i){const size=Math.max(1,wave[i]/max*(h*.36));ctx.globalAlpha=.55+.35*wave[i]/max;ctx.fillRect(i*w/wave.length,h/2-size,Math.max(1,w/wave.length-2),size*2);}ctx.globalAlpha=1;}
return {norm,actual,arc,bindKnobs,drawWaveform};
};
