// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Nicolas Wehmeyer
'use strict';
const specs=[[-24,24,0,.01,'st'],[.5,2,1,.001,'×'],[-12,12,0,.01,'st'],[.1,2000,8,.1,'ms',3],[1,5000,240,1,'ms',3],[-60,6,-9,.1,'dB'],[0,1,0,1,''],[24,103,60,1,''],[0,2,1,1,''],[0,2,2,1,''],[0,1,0,1,'']];
const values=specs.map(x=>x[2]);
const {norm,actual,arc,bindKnobs,drawWaveform}=createChronoBentControls({specs,values,send,gesture,format});
const $=id=>document.getElementById(id);
let ready=false,preparing=true,dirty=false,wave=Array(256).fill(0),lastRevision=0;
const active=new Set();
function bridge(message){if(typeof IPlugSendMsg==='function') IPlugSendMsg(message);}
function gesture(i,begin){bridge({msg:begin?'BPCFUI':'EPCFUI',paramIdx:i});}
function send(i,value){if(i===2 && values[10]===0)send(10,1);const s=specs[i];values[i]=Math.max(s[0],Math.min(s[1],Math.round(value/s[3])*s[3]));bridge({msg:'SPVFUI',paramIdx:i,value:norm(i,values[i])});if([0,1,2,7,8,9,10].includes(i)) setDirty(true);paint(i);}
function message(tag){bridge({msg:'SAMFUI',msgTag:tag,ctrlTag:-1,data:''});}
function format(i,value){if(i===0||i===2)return `${value>0?'+':value<0?'−':''}${Math.abs(value).toFixed(2)} st`;if(i===1)return `${value.toFixed(3)} ×`;if(i===3||i===4)return value>=1000?`${(value/1000).toFixed(2)} s`:`${value.toFixed(value<10?1:0)} ms`;return `${value.toFixed(1)} dB`;}
function paint(i){const el=document.querySelector(`.knob-unit[data-param="${i}"]`);if(el){const n=norm(i,values[i]);el.style.setProperty('--rotation',`${-135+270*n}deg`);el.querySelector('.fill').setAttribute('d',arc(n));const knob=el.querySelector('.knob');knob.setAttribute('aria-valuenow',values[i]);knob.setAttribute('aria-valuetext',format(i,values[i]));if(document.activeElement!==el.querySelector('.value'))el.querySelector('.value').value=format(i,values[i]);}if(i===5){$('gain').value=norm(i,values[i]);$('gain-value').textContent=format(i,values[i]);}if(i===6||i===10)$(i===6?'loop':'formants').setAttribute('aria-pressed',values[i]?'true':'false');if(i===8||i===9)$(i===8?'profile':'transients').selectedIndex=values[i];if(i===7){$('root').value=values[i];$('root-name').textContent=noteName(values[i]);keyboard();}}
function setDirty(value){dirty=value;document.body.classList.toggle('dirty',value);$('apply').disabled=!value||preparing;$('apply').innerHTML=preparing?'PREPARING… <span>↗</span>':value?'APPLY SOUND <span>↗</span>':'UP TO DATE <span>↗</span>';if(value&&!preparing)$('status').textContent='SOUND CHANGED · APPLY TO PLAY';}
bindKnobs();
$('gain').addEventListener('pointerdown',()=>gesture(5,true));$('gain').addEventListener('input',()=>send(5,actual(5,Number($('gain').value))));$('gain').addEventListener('change',()=>gesture(5,false));
for(const [id,i] of [['loop',6],['formants',10]])$(id).addEventListener('click',()=>{gesture(i,true);send(i,values[i]?0:1);gesture(i,false);});
for(const [id,i] of [['root',7],['profile',8],['transients',9]])$(id).addEventListener('change',()=>{gesture(i,true);send(i,id==='root'?Number($(id).value):$(id).selectedIndex);gesture(i,false);});
$('apply').addEventListener('click',()=>{message(1);preparing=true;setDirty(false);$('status').textContent='PREPARING YOUR SOUND…';});
$('load').addEventListener('click',()=>message(2));
$('tune').addEventListener('click',()=>message(20));
$('presets').addEventListener('click',()=>{const open=$('preset-menu').hidden;$('preset-menu').hidden=!open;$('presets').setAttribute('aria-expanded',String(open));});
for(const button of document.querySelectorAll('[data-preset]'))button.addEventListener('click',()=>{message(10+Number(button.dataset.preset));$('preset-menu').hidden=true;$('presets').setAttribute('aria-expanded','false');preparing=true;setDirty(false);});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.sample-name')){$('preset-menu').hidden=true;$('presets').setAttribute('aria-expanded','false');}});
function noteName(n){n=Math.round(n);return ['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'][n%12]+(Math.floor(n/12)-1);}
function note(n,on){if(on){if(active.has(n))return;active.add(n);}else active.delete(n);bridge({msg:'SMMFUI',statusByte:on?144:128,dataByte1:n,dataByte2:on?100:0});document.querySelector(`[data-note="${n}"]`)?.classList.toggle('active',on);}
function stopKeys(){for(const n of [...active])note(n,false);}
function keyboard(){stopKeys();const root=Math.round(values[7]),keys=[];for(let n=root-24;n<=root+24;++n)keys.push(n);const white=keys.filter(n=>![1,3,6,8,10].includes(n%12));$('keyboard').replaceChildren();let whites=0;for(const n of keys){const black=[1,3,6,8,10].includes(n%12);const key=document.createElement('button');key.className=`key${black?' black':''}${n===root?' root':''}`;key.dataset.note=n;key.setAttribute('aria-label',`Play ${noteName(n)}`);key.tabIndex=-1;if(black){key.style.left=`calc(${100*whites/white.length}% - 1.15%)`;}else{++whites;if(n%12===0){const text=document.createElement('span');text.textContent=noteName(n);key.append(text);}}key.addEventListener('pointerdown',e=>{key.setPointerCapture(e.pointerId);note(n,true);});key.addEventListener('pointerup',()=>note(n,false));key.addEventListener('pointercancel',()=>note(n,false));key.addEventListener('lostpointercapture',()=>note(n,false));$('keyboard').append(key);}}
const typingMap={a:0,w:1,s:2,e:3,d:4,f:5,t:6,g:7,y:8,h:9,u:10,j:11,k:12};const typingHeld=new Map();
document.addEventListener('keydown',e=>{if(e.target.matches('input,select')||e.metaKey||e.ctrlKey||e.altKey||e.repeat)return;if(typingMap[e.key]!==undefined){e.preventDefault();const n=values[7]+typingMap[e.key];typingHeld.set(e.key,n);note(n,true);}});
document.addEventListener('keyup',e=>{if(typingHeld.has(e.key)){note(typingHeld.get(e.key),false);typingHeld.delete(e.key);}});window.addEventListener('blur',()=>{stopKeys();typingHeld.clear();});
function draw(){drawWaveform($('waveform'),wave);}
window.SPVFD=(i,value)=>{if(!specs[i]||!Number.isFinite(value))return;const s=specs[i];values[i]=Math.max(s[0],Math.min(s[1],Math.round(actual(i,value)/s[3])*s[3]));paint(i);};
window.SAMFD=(tag,size,data)=>{if(tag!==100)return;try{const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0));update(JSON.parse(new TextDecoder().decode(bytes)));}catch(error){$('notice').textContent='Display update unavailable';}};
window.SCMFD=()=>{};window.SMMFD=()=>{};window.SSMFD=()=>{};
function update(s){ready=s.ready;$('tune').disabled=!s.ready||s.preparing;$('tune').textContent=s.tuned?'NOTE STUDIO · ON ↗':'NOTE STUDIO ↗';preparing=s.preparing;if(s.revision!==lastRevision){lastRevision=s.revision;const p=s.applied;if(p){const formant=values[10]?Math.pow(2,values[2]/12):0;setDirty(Math.abs(values[0]-p.pitch)>.005||Math.abs(values[1]-p.tempo)>.0005||Math.abs(formant-p.formant)>.0001||values[7]!==p.root||values[8]!==p.profile||values[9]!==p.transients);}else setDirty(false);}setDirty(dirty);$('sample-name').textContent=s.name||'Your next sound';$('sample-meta').textContent=s.rate?`${s.duration.toFixed(2)} SEC  /  ${(s.rate/1000).toFixed(1)} kHz  /  STEREO`:'SAMPLE INSTRUMENT';$('status').textContent=s.error?s.error.toUpperCase():preparing?'PREPARING YOUR SOUND…':dirty?'SOUND CHANGED · APPLY TO PLAY':ready?'READY TO PLAY · '+noteName(values[7])+' ROOT':'CHOOSE A SAMPLE TO BEGIN';$('progress-text').textContent=preparing?`${Math.round(s.progress*100)}%`:'';$('progress').style.width=preparing?`${s.progress*100}%`:'0';$('voice-count').textContent=`${s.voices} / 4 VOICES`;for(const key of document.querySelectorAll('[data-note]')){const n=Number(key.dataset.note);key.classList.toggle('active',active.has(n)||(s.notes||[]).includes(n));}$('voice-dots').textContent=Array.from({length:4},(_,i)=>i<s.voices?'●':'○').join(' ');$('meter').style.width=`${Math.min(100,s.peak*100)}%`;if(s.waveform){wave=s.waveform;draw();}const notice=s.error|| (s.underruns?'STREAM UNDERRUN · TRY FEWER VOICES OR A LARGER HOST BUFFER':s.dropped?'MIDI QUEUE FULL · SOME NOTES WERE SKIPPED':'INDEPENDENT PITCH & TIME · MADE TO EXPLORE');$('notice').textContent=notice;$('notice').classList.toggle('error',!!s.error||s.underruns>0||s.dropped>0);}
values.forEach((_,i)=>paint(i));draw();
if(new URLSearchParams(location.search).has('preview')){wave=Array.from({length:256},(_,i)=>Math.exp(-i/105)*(.3+.38*Math.abs(Math.sin(i*1.7))+.2*Math.abs(Math.sin(i*.13)))*Math.min(1,i/4));update({ready:true,preparing:false,revision:1,name:'Glass Circuit',rate:48000,duration:1.5,voices:0,peak:0,waveform:wave,progress:1,error:'',underruns:0,dropped:0});}
