// SPDX-License-Identifier: MIT
#define PLUG_NAME "ChronoBent"
#define PLUG_MFR "Nicolas Wehmeyer"
#define PLUG_VERSION_HEX 0x00000500
#define PLUG_VERSION_STR "0.5.0"
#define PLUG_UNIQUE_ID 'ChBn'
#define PLUG_MFR_ID 'NWeh'
#define PLUG_URL_STR "https://github.com/nicolaswehmeyer/ChronoBent"
#define PLUG_EMAIL_STR ""
#define PLUG_COPYRIGHT_STR "Copyright 2026 Nicolas Wehmeyer"
#define PLUG_CLASS_NAME ChronoBentPlugin
#define BUNDLE_NAME "ChronoBent"
#define BUNDLE_MFR "nicolaswehmeyer"
#define BUNDLE_DOMAIN "com"
#define SHARED_RESOURCES_SUBPATH "ChronoBent"
#define PLUG_CHANNEL_IO "0-2"
#define PLUG_LATENCY 0
#define PLUG_TYPE 1
#define PLUG_DOES_MIDI_IN 1
#define PLUG_DOES_MIDI_OUT 0
#define PLUG_DOES_MPE 0
#define PLUG_DOES_STATE_CHUNKS 1
#define PLUG_HAS_UI 1
#define PLUG_WIDTH 1040
#define PLUG_HEIGHT 720
#define PLUG_FPS 20
#define PLUG_SHARED_RESOURCES 0
#define PLUG_HOST_RESIZE 0
#define AUV2_ENTRY ChronoBent_Entry
#define AUV2_ENTRY_STR "ChronoBent_Entry"
#define AUV2_FACTORY ChronoBent_Factory
#define AUV2_VIEW_CLASS ChronoBent_View
#define AUV2_VIEW_CLASS_STR "ChronoBent_View"
#define VST3_SUBCATEGORY "Instrument|Sampler"
